[versions]
turbine = "1.1.0"
kotlin = "1.8.10"
agp = "8.4.1"
safe-args = "2.6.0"
google-services = "4.3.15"
crashlytics = "2.8.1"

[libraries]
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "safe-args" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }